# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dal < Formula
  desc ""
  homepage "https://github.com/supasheet/homebrew-dal"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/supasheet/dal/releases/download/v0.0.3/dal_0.0.3_Darwin_arm64.tar.gz"
      sha256 "9617bf66ffefb192a01850edd10ab9aee3f41157032fc413670cd727bbb15c34"

      def install
        bin.install "dal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/supasheet/dal/releases/download/v0.0.3/dal_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "233cdef5b438de2a205fbca5870fb1a5a038270dc519ee491dd9b1ecec02314f"

      def install
        bin.install "dal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/supasheet/dal/releases/download/v0.0.3/dal_0.0.3_Linux_arm64.tar.gz"
      sha256 "71b7799fa42d332920cff784595fef9d60adb74dfde25fa244736ea1c35e7dea"

      def install
        bin.install "dal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/supasheet/dal/releases/download/v0.0.3/dal_0.0.3_Linux_x86_64.tar.gz"
      sha256 "85e77af7a9da77b7e3e24def9384e2a8046761452583069a965c3d0b6150be9c"

      def install
        bin.install "dal"
      end
    end
  end
end
